"""U1 — pool de lieux en C liés à une boisson, coordonnées Wikipedia (API, cache solveurB_coords_cache.json).
Familles: W=vin/appellation, S=spiritueux/liqueur, B=bière/cidre, E=eau/source, G=Graal/coupe/calice, M=lieu monastique-boisson.
pays: FR ES PT AD UK IE. Ordre voulu: fixé A PRIORI dans U1_chaines.py (avant mesure)."""
import sys, json
sys.path.insert(0, ".")
from solveurB_geo import wiki_coords
sys.stdout.reconfigure(encoding="utf-8")
POOL = {  # nom: (titre wikipedia, lang, famille, pays, note)
 "Cognac": ("Cognac, France","en","S","FR","cognac"),
 "Chablis": ("Chablis","en","W","FR","vin"),
 "Cahors": ("Cahors","en","W","FR","vin (moines, Cahors=vin noir)"),
 "Cassis": ("Cassis, Bouches-du-Rhône","en","W","FR","vin+liqueur"),
 "Chinon": ("Chinon","en","W","FR","vin"),
 "Chateauneuf-du-Pape": ("Châteauneuf-du-Pape","en","W","FR","vin, papes"),
 "Condrieu": ("Condrieu","en","W","FR","vin"),
 "Cornas": ("Cornas","en","W","FR","vin"),
 "Cadillac": ("Cadillac, Gironde","en","W","FR","vin liquoreux"),
 "Cambremer": ("Cambremer","en","B","FR","cidre/Pays d'Auge"),
 "Chambery": ("Chambéry","en","S","FR","vermouth Dolin"),
 "Chartreuse": ("Grande Chartreuse","en","S","FR","liqueur, chartreux (moines)"),
 "Voiron-Chartreuse": ("Voiron","en","S","FR","distillerie"),
 "Cointreau-Angers": ("Angers","en","S","FR","Cointreau (pas en C)"),
 "Chalon": ("Chalon-sur-Saône","en","W","FR","Côte chalonnaise"),
 "Chambolle": ("Chambolle-Musigny","en","W","FR","vin"),
 "Chassagne": ("Chassagne-Montrachet","en","W","FR","vin"),
 "Cheverny": ("Cour-Cheverny","en","W","FR","vin"),
 "Cerons": ("Cérons","en","W","FR","vin"),
 "Collioure": ("Collioure","en","W","FR","vin (Banyuls)"),
 "Corbieres": ("Corbières","en","W","FR","vin"),
 "Champagne-Chalons": ("Châlons-en-Champagne","en","W","FR","Champagne"),
 "Cramant": ("Cramant","en","W","FR","Champagne grand cru"),
 "Chigny": ("Chigny-les-Roses","en","W","FR","Champagne"),
 "Chouilly": ("Chouilly","en","W","FR","Champagne"),
 "Chavot": ("Chavot-Courcourt","en","W","FR","Champagne"),
 "Chaumont-Champagne": ("Chaumont, Haute-Marne","en","W","FR","Champagne (Haute-Marne)"),
 "Calvados": ("Calvados (department)","en","S","FR","dpt Calvados"),
 "Caen": ("Caen","en","S","FR","chef-lieu Calvados"),
 "Cerisy": ("Cerisy-la-Forêt","en","B","FR","cidre"),
 "Contrexeville": ("Contrexéville","en","E","FR","eau"),
 "Cauterets": ("Cauterets","en","E","FR","eau thermale"),
 "Chatel-Guyon": ("Châtel-Guyon","en","E","FR","eau"),
 "Chateldon": ("Châteldon","en","E","FR","eau"),
 "Cransac": ("Cransac","en","E","FR","eau"),
 "Capvern": ("Capvern","en","E","FR","eau"),
 "Cambo": ("Cambo-les-Bains","en","E","FR","thermes"),
 "Chaudes-Aigues": ("Chaudes-Aigues","en","E","FR","eau chaude"),
 "Cusset": ("Cusset","en","E","FR","Vichy Célestins?"),
 "Camarès": ("Camarès","en","E","FR","eau"),
 "Cluny": ("Cluny","en","M","FR","abbaye (vin)"),
 "Citeaux": ("Cîteaux Abbey","en","M","FR","cistercien, Clos de Vougeot"),
 "Clairvaux": ("Clairvaux Abbey","en","M","FR","Bernard, vin/Champagne"),
 "Clos-de-Vougeot": ("Château du Clos de Vougeot","en","M","FR","cistercien vin"),
 "Cadouin": ("Cadouin Abbey","en","G","FR","Saint Suaire; pas boisson"),
 "Chaource": ("Chaource","en","B","FR","Chaource=fromage"),
 "Campbeltown": ("Campbeltown","en","S","UK","whisky"),
 "Cardhu": ("Cardhu distillery","en","S","UK","whisky"),
 "Cragganmore": ("Cragganmore distillery","en","S","UK","whisky"),
 "Clynelish": ("Clynelish distillery","en","S","UK","whisky"),
 "Caol Ila": ("Caol Ila distillery","en","S","UK","whisky"),
 "Cambus": ("Cambus","en","S","UK","distillerie"),
 "Cork": ("Cork (city)","en","B","IE","Murphy's, Beamish"),
 "Carlow": ("Carlow","en","B","IE","O'Hara's"),
 "Clonmel": ("Clonmel","en","B","IE","Bulmers cidre"),
 "Cashel": ("Cashel, County Tipperary","en","G","IE","rock of Cashel"),
 "Coleraine": ("Coleraine","en","S","UK","whisky Bushmills"),
 "Cooley": ("Cooley distillery","en","S","IE","whiskey"),
 "Caerphilly": ("Caerphilly","en","B","UK","fromage"),
 "Cambridge": ("Cambridge","en","B","UK","Cam"),
 "Carinena": ("Cariñena","en","W","ES","vin"),
 "Calatayud": ("Calatayud","en","W","ES","vin"),
 "Cigales": ("Cigales","en","W","ES","vin"),
 "Chinchon": ("Chinchón","en","S","ES","anis"),
 "Cazalla": ("Cazalla de la Sierra","en","S","ES","anis"),
 "Cangas-Narcea": ("Cangas del Narcea","en","W","ES","vin/cidre"),
 "Cebreiro": ("O Cebreiro","en","G","ES","Graal de Galice"),
 "Cadiz": ("Cádiz","en","W","ES","Xérès/Sherry triangle"),
 "Campo-de-Borja": ("Borja, Aragon","en","W","ES","vin (pas en C)"),
 "Cebreros": ("Cebreros","en","W","ES","vin"),
 "Castellon-Peñiscola": ("Peñíscola","en","W","ES","pape Luna (pas C)"),
 "Cuenca": ("Cuenca, Spain","en","W","ES","-"),
 "Cudillero": ("Cudillero","en","B","ES","cidre Asturies"),
 "Colares": ("Colares","en","W","PT","vin"),
 "Carcavelos": ("Carcavelos","en","W","PT","vin"),
 "Cartaxo": ("Cartaxo","en","W","PT","vin"),
 "Chaves": ("Chaves, Portugal","en","E","PT","eau Vidago, Pedras Salgadas"),
 "Coimbra": ("Coimbra","en","W","PT","-"),
 "Canillo": ("Canillo","en","E","AD","-"),
 "Carnac": ("Carnac","en","-","FR","É5"),
 "Compostelle": ("Santiago de Compostela","en","G","ES","coquille"),
 "Champagne-Epernay": ("Épernay","en","W","FR","(E, pas C)"),
 "Reims": ("Reims","en","W","FR","(R, pas C)"),
}
if __name__ == "__main__":
    r = wiki_coords([v[0] for v in POOL.values()], "en")
    out = {}
    for k, v in POOL.items():
        c = r[v[0]]
        out[k] = {"lat": c[0], "lon": c[1], "wiki": c[2]} if c else None
        print(f"{k:22s} {v[2]} {v[3]} ", (f"{c[0]:.4f},{c[1]:.4f} <{c[2]}>" if c else "AUCUNE COORD"))
    json.dump(out, open("U1_coords.json","w",encoding="utf-8"), ensure_ascii=False, indent=1)
