LISTS={
'preux':['Hector','Alexandre','Cesar','Josue','David','Judas Maccabee','Judas Macchabee','Maccabee','Arthur','Charlemagne','Godefroy de Bouillon','Godefroy','Bouillon','Godefroi'],
'grec':['Zeus','Hera','Poseidon','Demeter','Hestia','Hades','Athena','Apollon','Artemis','Ares','Aphrodite','Hephaistos','Hermes','Dionysos','Cronos','Kronos','Rhea','Ouranos','Uranus','Gaia','Gea','Pan','Eros','Nyx','Erebe','Chaos','Thanatos','Hypnos','Hecate','Persephone','Helios','Selene','Eos','Atlas','Prometheus','Nemesis','Tyche','Iris','Hebe','Eole','Triton','Nereus','Thetis','Titan','Oceanos','Ocean','Themis','Mnemosyne','Phoebe','Cybele','Asclepios','Heracles','Herakles','Hercule','Perseus','Orion','Caelus','Coeus','Crios','Hyperion','Japet','Iapetos','Thea','Tethys','Cerbere','Charon','Cerberus','Chiron','Circe','Calypso','Castor','Pollux','Cassandre','Clio','Calliope','Cyclope'],
'romain':['Jupiter','Junon','Neptune','Ceres','Vesta','Pluton','Minerve','Apollon','Diane','Mars','Venus','Vulcain','Mercure','Bacchus','Saturne','Ops','Uranus','Caelus','Coelus','Terra','Tellus','Janus','Faune','Flore','Aurore','Sol','Luna','Lune','Soleil','Cupidon','Amour','Psyche','Fortuna','Victoria','Bellone','Proserpine','Hercule','Quirinus','Silvain','Cybele','Vertumne','Pomone','Libitina','Dispater','Dis Pater','Iuppiter','Iovis','Diespiter','Juppiter','Ceres','Comus','Consus','Carmenta','Cardea','Concordia'],
'nordique':['Odin','Thor','Loki','Freya','Freyja','Frigg','Tyr','Baldr','Balder','Heimdall','Njord','Frey','Freyr','Bragi','Idunn','Sif','Hel','Ymir','Vidar','Vali','Ull','Forseti','Hod','Skadi','Aegir','Ran','Jord','Mani','Sol','Fenrir','Odhin','Wotan','Woden','Donar','Wodan','Tiw','Frige'],
'egypte':['Ra','Re','Amon','Amon-Ra','Osiris','Isis','Horus','Seth','Set','Anubis','Thot','Thoth','Hathor','Bastet','Sekhmet','Ptah','Nout','Geb','Shou','Tefnout','Nephtys','Sobek','Apis','Aton','Atoum','Maat','Khnoum','Khonsou','Min','Bes'],
'celte':['Lug','Lugh','Taranis','Teutates','Esus','Belenos','Cernunnos','Epona','Ogmios','Dagda','Brigit','Morrigan','Nuada','Danu','Lir','Manannan','Cernunos','Sucellus','Nantosuelta','Rosmerta','Camulos','Toutatis','Belisama','Maponos','Grannus','Sirona','Nodens','Ceridwen','Arawn','Rhiannon','Bran','Cocidius','Cathubodua','Coventina'],
'planetes':['Soleil','Lune','Mars','Mercure','Jupiter','Venus','Saturne','Uranus','Neptune','Pluton','Terre'],
'jours':['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'],
'jours_lat':['Dies Lunae','Dies Martis','Dies Mercurii','Dies Iovis','Dies Veneris','Dies Saturni','Dies Solis'],
'zodiaque':['Belier','Taureau','Gemeaux','Cancer','Lion','Vierge','Balance','Scorpion','Sagittaire','Capricorne','Verseau','Poissons'],
'templiers':['Hugues de Payns','Payens','Godefroi de Saint-Omer','Bernard de Clairvaux','Jacques de Molay','Molay','Templier','Temple','Hospitaliers','Baudouin','Urbain','Urbain II','Eudes de Chatillon','Pierre lErmite','Raymond de Saint-Gilles','Bohemond','Tancrede','Godefroy'],
'saintpere':['Pater Noster','Notre Pere','Pere','Cieux','Ciel','Caelum','Pater','Libera nos a malo','Amen'],
}
